# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c46c652bbf90aa13ee483c088be0f8a639bb926aef19b10a7b9459e194ebb12853c9e891064c2571dd3859678a32faffdc7365d0df35b4875938232313d3a0bc

test:
  secret_key_base: 46ac76839bd626880689f6c27f10bff0baac93b6d39ae0afa041f0f2512cdf23207737d569f1d22dcf18a525b75023badd1761e04899ee0bb5463241c0454fa5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
